Repository annadrobek/ShoppingList, pull requests merged in 2023-03, with the labels that each got.

#2 Dodanie strony głównej
  .gitignore
  nb-configuration.xml
  pom.xml
  src/main/java/edu/shoppinglist/demo/controllers/HomeController.java
  src/main/java/edu/shoppinglist/demo/merchandise/Item.java
  src/main/java/edu/shoppinglist/demo/repositories/ItemRepository.java
  src/main/resources/application.properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/add.html
  src/main/resources/templates/home.html
  src/main/webapp/META-INF/context.xml
Labels: enhancement

#4 Update home.html
  src/main/resources/templates/home.html
Labels: enhancement

#6 Dodanie linków
  src/main/java/edu/shoppinglist/demo/controllers/HomeController.java
  src/main/resources/application.properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/add.html
  src/main/resources/templates/error.html
  src/main/resources/templates/home.html
Labels: enhancement

#8 Kolejne html-e
  src/main/resources/static/css/style.css
  src/main/resources/static/images/image1.png
  src/main/resources/static/images/image2.png
  src/main/resources/static/images/image3.png
  src/main/resources/static/images/image5.png
  src/main/resources/templates/add.html
  src/main/resources/templates/home.html
Labels: enhancement

#9 Dodanie kontrolera i encji listy
  src/main/java/edu/shoppinglist/demo/controllers/AddListController.java
  src/main/java/edu/shoppinglist/demo/merchandise/List.java
  src/main/java/edu/shoppinglist/demo/repositories/ListsRepository.java
  src/main/resources/application.properties
Labels: enhancement

#10 Test zawartości strony
  jshell.history
  src/main/resources/application.properties
  src/test/java/edu/shoppinglist/demo/ShoppingListDemoApplicationTests.java
  src/test/java/edu/shoppinglist/demo/ShopplingListDemoDefaultPageContains.java
Labels: enhancement, test

#11 Rozbudowa części kontrolera
  pom.xml
  src/main/java/edu/shoppinglist/demo/controllers/HomeController.java
  src/main/java/edu/shoppinglist/demo/controllers/ListOperationService.java
  src/main/java/edu/shoppinglist/demo/controllers/QRCodeGenerator.java
  src/main/java/edu/shoppinglist/demo/merchandise/ShoppingList.java
  src/main/java/edu/shoppinglist/demo/repositories/ListsRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/add.html
  src/main/resources/templates/edit_list.html
  src/main/resources/templates/home.html
  src/main/resources/templates/listsManager.html
  src/main/resources/templates/qrcode.html
Labels: enhancement, help wanted, question
